version: "3.9"

services:
  backend:
    build: .
    container_name: blog_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://blog:123@db:5432/blog_db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: blog_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: blog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmins:
    image: dpage/pgadmin4
    container_name: blog_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: namra@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:
